// Contenu rédactionnel du chapitre. Aucun chiffre tabulé ou tracé ici :
// tout vient de ./data.ts. Voir CLAUDE.md, règle 2.
import { chapterComponents, Definition, Question, Source } from '@/components'
import type { RenderMode } from '@/components'
import { series, tables } from './data'

export default function Content({ mode = 'page' }: { mode?: RenderMode }) {
  const { DataTable } = chapterComponents({ tables, series, mode })

  return (
    <>

<Question id="s20-q1" title="De quoi on parle, en une page"><p>Chaque année, l'État, les collectivités et la Sécurité sociale dépensent ensemble environ <strong>1 670 milliards d'euros</strong>. C'est un chiffre trop gros pour vouloir dire quelque chose, alors ramenons-le à une personne : cela fait à peu près <strong>24 000 € par habitant et par an</strong>. Pour toi, pour ta mère, pour ton petit frère, pour ta grand-mère : 24 000 € chacun.</p><p>Cet argent ne part pas dans une administration mystérieuse. Il part très majoritairement vers des gens. Sur 100 € dépensés :</p><DataTable id="sur-100-de-depense-publique" /><Source ids={["eurostat-gov-10a-exp-2"]} /><p>Deux lignes font <strong>58 € sur 100</strong> : les retraites et la santé. Retiens ça, parce que c'est la clé de presque tout le reste. Quand quelqu'un promet de « faire des économies » sans toucher aux retraites ni à la santé, il promet de faire des économies sur les 42 € restants — dont il faut encore enlever les intérêts de la dette, qu'on ne peut pas ne pas payer.</p></Question>


<Question id="s20-q2" title="Pourquoi la France emprunte tous les ans"><p>L'État dépense <strong>57 € pour 100 € de richesse produite</strong> dans le pays, et il en encaisse <strong>52</strong>. Il manque <strong>5 €</strong>. Chaque année. On les emprunte.</p><p>Ce n'est pas nouveau et ce n'est pas la faute d'un gouvernement en particulier : <strong>la France n'a pas voté un budget à l'équilibre depuis 1974</strong>. Cinquante ans. Tous les présidents, de droite comme de gauche, ont emprunté.</p><p>Résultat : la dette publique atteint aujourd'hui <strong>environ 115 % de tout ce que le pays produit en un an</strong>. Si la France était un ménage qui gagne 30 000 € par an, elle devrait 34 500 €.</p><Definition title={"« Et alors ? On peut vivre avec des dettes. »"}><p>C'est vrai, et un État n'est pas un ménage : il ne meurt pas, il peut emprunter indéfiniment tant qu'on lui prête. Le problème n'est pas moral, il est arithmétique. Plus la dette est grosse, plus les <b>intérêts</b> coûtent cher. La France paie déjà environ <b>60 milliards d'euros d'intérêts par an</b> — davantage que le budget de la Défense, à peu près autant que celui de l'Éducation nationale. Cet argent ne construit rien, ne soigne personne et n'enseigne à personne. Il part chez ceux qui ont prêté.</p><p>Et surtout : <b>c'est de l'argent que ta génération devra payer</b> pour des dépenses faites avant elle. C'est le vrai sujet du débat, et il est légitime que tu t'y intéresses.</p></Definition></Question>


<Question id="s20-q3" title="Le vrai problème français : on produit moins que nos voisins"><p>Voilà le point le plus important, et le moins discuté. Depuis vingt ans, la France s'appauvrit <em>relativement</em> à ses voisins. En 2005, un Français produisait 13 % de plus que la moyenne européenne. En 2024, il produit <strong>1 % de moins</strong>.</p><p>La question est : pourquoi ? Et la réponse est surprenante, parce qu'elle n'est pas celle qu'on entend d'habitude.</p><ol className="check"><li><b>Ce n'est pas que les Français travaillent mal.</b> Quand un Français travaille une heure, il produit à peu près autant qu'un Allemand — un peu moins, mais l'écart est faible.</li><li><b>Ce n'est pas non plus qu'ils travaillent peu <em>quand</em> ils travaillent.</b> Un Français en emploi travaille <b>1 512 heures par an, un Allemand 1 345</b>. Le Français travaille <em>plus</em> — parce qu'en Allemagne beaucoup de gens sont à temps partiel.</li><li><b>Le vrai écart est là : moins de Français travaillent.</b> 69 % des 15-64 ans ont un emploi en France, contre 77 % en Allemagne et 82 % aux Pays-Bas. Et le trou est aux deux bouts de la vie : chez les jeunes (34 % contre 51 %) et chez les seniors (60 % contre 75 %).</li><li><b>Et il y a plus de retraités.</b> 22 % des Français ont plus de 65 ans. Plus de gens à la retraite, moins de gens qui produisent : le PIB par habitant baisse mécaniquement, même si personne ne travaille moins bien.</li></ol><p>Autrement dit : <strong>le problème n'est pas la paresse, c'est l'arithmétique.</strong> Moins de gens produisent la richesse qui doit faire vivre tout le monde. Et comme il y a plus de retraités à payer, la dépense sociale augmente pendant que la richesse produite augmente moins vite. Les deux courbes s'écartent. C'est ça, la situation de la France.</p></Question>


<Question id="s20-q4" title="Cinq idées reçues que les chiffres ne confirment pas"><div className="tcard"><h4>« La France dépense beaucoup plus que les autres »</h4><p className="kf">Vrai en pourcentage de la richesse produite (2<sup>e</sup> d'Europe). <b>Beaucoup moins vrai par habitant</b> : corrigée du niveau des prix, la dépense française est de 22 321 unités de pouvoir d'achat par habitant contre 22 937 en Allemagne. Nous sommes <em>derrière</em> l'Allemagne. Le pourcentage du PIB mesure autant la faiblesse de ce qu'on produit que la générosité de ce qu'on dépense.</p></div><div className="tcard"><h4>« Les Allemands dépensent moins pour leur protection sociale »</h4><p className="kf">Faux en niveau. L'Allemagne dépense <b>10 575 € par habitant</b> pour la protection sociale, la France <b>10 077 €</b>. Elle dépense <em>plus</em> que nous par personne, et moins en part de sa richesse — parce qu'elle est plus riche.</p></div><div className="tcard"><h4>« L'administration française est un gouffre inefficace »</h4><p className="kf">Le dossier ne le trouve pas. Sur la plupart des fonctions, la France est dans la moyenne européenne rapportée à sa population. Il y a de vraies exceptions, dans les deux sens — la France a par exemple <b>beaucoup moins de juges par habitant</b> que ses voisins, ce qui explique en partie la lenteur de la justice.</p></div><div className="tcard"><h4>« L'immigration coûte une fortune »</h4><p className="kf">Personne ne le sait précisément, et c'est la vraie réponse. Selon la convention comptable retenue — comment on répartit le coût de l'armée et des intérêts de la dette — la même étude de l'OCDE donne <b>+1,02 % ou −0,85 % du PIB</b>. Ce sur quoi les travaux scientifiques s'accordent : l'effet tient dans une fourchette de <b>plus ou moins 0,5 % de la richesse nationale</b>, quand le déficit, lui, vaut 5,8 %. Ce n'est ni la cause du problème ni sa solution.</p></div><div className="tcard"><h4>« On dépense trop pour l'école »</h4><p className="kf">L'inverse, si on regarde par élève. La France dépense <b>plus en part du PIB</b> que l'Allemagne, parce qu'elle a plus de jeunes — mais <b>moins par élève</b> : 11 326 $ contre 13 190 $ au primaire. Et elle a des classes un peu plus chargées que la moyenne. L'argent de l'éducation existe ; il est réparti différemment.</p></div></Question>


<Question id="s20-q5" title="Ce que ça veut dire pour ta génération"><p>Trois choses, sans dramatiser et sans te mentir.</p><p><strong>D'abord, tu hérites d'une facture.</strong> La dette a été construite sur cinquante ans par des gens qui ne la rembourseront pas. Ce n'est pas une catastrophe imminente — la France emprunte sans difficulté — mais c'est une contrainte : chaque euro d'intérêt est un euro qui ne va pas à un hôpital, à un professeur ou à un train.</p><p><strong>Ensuite, le système repose sur toi.</strong> Les retraites françaises fonctionnent par répartition : ceux qui travaillent aujourd'hui paient les pensions de ceux qui sont à la retraite aujourd'hui. En 1960, il y avait 4 actifs par retraité. Aujourd'hui, un peu plus de 1,7. Cela ne veut pas dire que le système va s'effondrer, mais que quelqu'un devra choisir entre trois options — travailler plus longtemps, cotiser davantage, ou toucher des pensions plus faibles. Il n'y a pas de quatrième porte, et tous les partis qui promettent le contraire promettent quelque chose d'arithmétiquement impossible.</p><p><strong>Enfin, et c'est la bonne nouvelle : rien de tout cela n'est une fatalité.</strong> Le principal problème français est le nombre de gens qui travaillent, pas leur productivité. Les Pays-Bas font travailler 82 % de leurs 15-64 ans en ayant une protection de l'emploi <em>plus</em> forte que la nôtre. Ce n'est donc pas un problème de nature, c'est un problème d'organisation. Ça se change.</p><Definition title={"Comment lire un discours politique, en trois réflexes"}><p><b>1. Demande toujours « rapporté à quoi ? »</b> « La France est 2<sup>e</sup> d'Europe pour la dépense publique » et « la France est 8<sup>e</sup> par habitant » sont vrais tous les deux. Celui qui choisit un seul des deux choisit sa conclusion avant son chiffre.</p><p><b>2. Sépare le fait du jugement.</b> « La France dépense 57 % du PIB » est un fait. « C'est trop » est une opinion. Les deux sont légitimes, mais on ne les discute pas de la même façon — un fait se vérifie, une opinion se débat.</p><p><b>3. Demande qui paie et sur combien d'années.</b> Une mesure « qui ne coûte rien » coûte toujours quelque chose à quelqu'un. Si personne ne peut te dire qui, c'est que le chiffrage n'existe pas.</p></Definition><p>Une dernière chose. Ce dossier compte environ deux cents fiches, et beaucoup se terminent par « on ne sait pas ». Ce n'est pas un aveu d'échec : c'est le résultat le plus utile. <strong>Une bonne partie du débat public porte sur des chiffres que personne ne mesure.</strong> Savoir lesquels, c'est déjà être mieux armé que la plupart des gens qui en parlent à la télévision.</p></Question>

    </>
  )
}
