// Contenu rédactionnel du chapitre. Aucun chiffre tabulé ou tracé ici :
// tout vient de ./data.ts. Voir CLAUDE.md, règle 2.
import { chapterComponents, Question } from '@/components'
import type { RenderMode } from '@/components'
import { series, tables } from './data'

export default function Content({ mode = 'page' }: { mode?: RenderMode }) {

  return (
    <>

<Question id="s19-q1" title="Les treize questions"><ol className="check"><li><b>Quel est le coût annuel ?</b> Un chiffrage sans horizon temporel ni régime de croisière ne veut rien dire.</li><li><b>Est-il cohérent avec les évaluations indépendantes ?</b> Comparer aux chiffrages de l'Institut Montaigne, de l'IPP, de l'OFCE ou de la Cour des comptes, en notant qui a intérêt à quel chiffre.</li><li><b>Qui gagne directement ?</b> Nommer les bénéficiaires, en nombre et en montant moyen.</li><li><b>Qui perd directement ?</b> Toute mesure a des perdants. Une proposition qui n'en identifie aucun est mal chiffrée ou mal présentée.</li><li><b>Comment est-elle financée ?</b> Nouvelle recette, économie identifiée, ou dette — et si dette, à quel coût d'intérêt.</li><li><b>Quel effet sur le déficit et la dette ?</b> En points de PIB : 10 Md€ représentent 0,33 point.</li><li><b>Quel effet sur l'emploi et la croissance ?</b> Avec le multiplicateur retenu, qui est une hypothèse et doit être explicité.</li><li><b>Quel effet sur le pouvoir d'achat ?</b> Et duquel : moyen, médian, par décile ?</li><li><b>Quels effets indirects ?</b> Captation par les prix (les APL), effets d'aubaine (l'apprentissage), report d'assiette, évasion.</li><li><b>Existe-t-il des exemples à l'étranger ?</b> Et ces pays ont-ils obtenu le résultat annoncé ?</li><li><b>Est-ce réalisable par une loi ordinaire ?</b> Ou faut-il une révision constitutionnelle, une renégociation européenne, une dénonciation de convention — c'est-à-dire un tout autre calendrier.</li><li><b>Qu'est-ce qui est fait, estimation, hypothèse ou affirmation politique ?</b> Les quatre sont légitimes ; les confondre ne l'est pas.</li><li><b>Quelles incertitudes, et peuvent-elles inverser le résultat ?</b> Une proposition dont la conclusion s'inverse selon une hypothèse de taux d'actualisation n'est pas robuste.</li></ol></Question>


<Question id="s19-q2" title="Deux formulations réutilisables"><div className="prompt"><span className="pl">Pour vérifier une affirmation</span>Vérifie cette affirmation avec les dernières données disponibles, en priorité Insee, Eurostat, OCDE, Cour des comptes ou autres sources publiques. Donne le chiffre, son évolution sur vingt ans et la comparaison européenne. Explique aussi ce qui pourrait rendre cette affirmation trompeuse même si le chiffre cité est exact.</div><div className="prompt"><span className="pl">Pour analyser une proposition</span>Analyse cette proposition sans prendre parti. Quel est son coût annuel ? Qui gagne ? Qui perd ? Comment est-elle financée ? Quel effet probable sur l'emploi, la croissance, les finances publiques et le pouvoir d'achat ? Existe-t-il des exemples dans d'autres pays ? Distingue les faits établis, les estimations, les hypothèses et les points controversés.</div></Question>


<Question id="s19-q3" title="Le principe de lecture"><p>Un chiffre isolé n'est presque jamais suffisant. Pour chaque sujet, chercher simultanément <strong>six choses</strong> : le niveau actuel, l'évolution historique, le dénominateur pertinent, la comparaison internationale, les causes possibles et les effets attendus des solutions.</p><p>Ce document en donne une illustration répétée, et c'est peut-être ce qu'il faut en retenir :</p><ol className="check"><li><b>« La France travaille moins »</b> est vrai ou faux selon qu'on rapporte les heures aux salariés à temps plein, à tous les emplois, ou à la population en âge de travailler. Les trois réponses figurent au thème 03, et elles sont contradictoires.</li><li><b>« La France dépense le plus »</b> est vrai en % du PIB (2ᵉ d'Europe) et faux par habitant (8ᵉ). L'écart mesure la faiblesse du PIB par tête, pas l'ampleur de la dépense.</li><li><b>« L'administration italienne coûte plus cher »</b> est vrai en brut et faux hors intérêts de la dette : l'Italie devient alors la plus légère des six pays comparés.</li><li><b>« Les inégalités françaises avant impôt sont les plus fortes d'Europe »</b> est un artefact de la comptabilisation des retraites publiques, pas une réalité sociale.</li><li><b>« Les enseignants français font peu d'heures »</b> est contredit par les données : 900 h au primaire contre 784 en moyenne OCDE.</li><li><b>« Il y a de plus en plus de fonctionnaires »</b> est faux rapporté à la population (+2,7 % en vingt ans) et vrai en composition (+20 % pour le territorial, −10 % pour l'État).</li></ol><p><strong>Le dénominateur est presque toujours l'endroit où se cache le désaccord.</strong></p></Question>

    </>
  )
}
